add docs for buf curl
bufbuild/docs.buf.build pull request #314
Opened 2023-01-06 21:47 UTC by jhump

See a preview of this documentation [here](https://docs-buf-build-git-jh-buf-curl-bufbuild.vercel.app/curl/usage).

Fixes TCN-990

2023-01-06 21:53 UTC, jhump commented on sidebars.js
> +            label: "Invoking RPCs",
It felt a little awkward to name a category in the sidebar "Curl" (or "cURL", "CURL", whatever). So I made it more descriptive. Thoughts?

2023-01-11 15:46 UTC, elliotmjackson commented on sidebars.js
> +            label: "Invoking RPCs",
It's an awkward sidebar, some are commands and others are ideas, things or categories. For this one, however... i think it's more awkward for this command to be a category. In saying that, this is a situation of the _least_ awkward option so its quite subjective.

2023-01-11 16:55 UTC, elliotmjackson requested changes
I think we should consider adding `buf curl` anywhere we mention `grpcurl` or `curl` in our marketing/docs sites

2023-01-11 16:55 UTC, elliotmjackson commented on docs/curl/usage.md
> +
something as simple as 
```sh
buf curl \
    --data '{"sentence": "I feel happy."}' \
    https://demo.connect.build/buf.connect.demo.eliza.v1.ElizaService/Say
```

2023-01-11 16:55 UTC, elliotmjackson commented on docs/curl/usage.md
> +
Personally, I like illustrative examples in documentation... something to support the preceding and succeeding english refer back to. The first example (L103-106) would be great here

2023-01-11 16:55 UTC, elliotmjackson commented on docs/curl/usage.md
> +the method being invoked is not a bidirectional streaming method.
this might be a great opportunity to highlight the benefits of connect, you do it somewhat indirectly
> gRPC protocol cannot be used with HTTP 1.1

but it's almost asking a direct "the beauty of connect means..."

2023-01-11 16:55 UTC, elliotmjackson commented on docs/curl/usage.md
> +## Request Data and Metadata
i think this section is a little tricky to digest, it might be better to chuck this into a `FEATURE`: Benefit list. Kind of like this...

`-d`, `--data`: The input request. If absent, an empty request is sent unless the method uses a request stream, in which case an empty stream is sent.
`-H`: ...

#### Input styles
`@`: rest of the flag value is interpreted as a filename from which to read the request body
...

2023-01-11 16:55 UTC, elliotmjackson commented on docs/curl/usage.md
> +[service](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md#known-implementations).
maybe a bit too much "magic" here loses the point, potentially doesnt even need the links 🤷‍♂️

2023-01-11 16:55 UTC, elliotmjackson commented on docs/curl/usage.md
> +a [BSR](../bsr/introduction.md) module.
Examples of `--schema` usage would round this section out... i went to look for examples in `build` and `generate` doing this to try and find what was meant by "same kind of inputs"

2023-01-11 16:55 UTC, elliotmjackson commented on docs/curl/usage.md
> +and method name for the server reflection protocol.
```suggestion
:::note
Server reflection does not work with HTTP 1.1 since the protocol relies on bidirectional
streaming. If server reflection is used, the assumed URL for the reflection service is the same as
the given RPC target URL, but with the last two path elements removed and replaced with the service
and method name for the server reflection protocol.
:::
```

2023-01-11 16:55 UTC, elliotmjackson commented on docs/curl/usage.md
> +the method being invoked is not a bidirectional streaming method.
```suggestion
flag. 

:::note
The gRPC protocol cannot be used with HTTP 1.1, but the other two can as long as
the method being invoked is not a bidirectional streaming method.
:::
```

2023-01-11 16:55 UTC, elliotmjackson commented on docs/curl/usage.md
> +the method being invoked is not a bidirectional streaming method.
https://docusaurus.io/docs/2.1.0/markdown-features/admonitions

2023-01-11 16:55 UTC, elliotmjackson commented on docs/curl/usage.md
> +and method name for the server reflection protocol.
https://docusaurus.io/docs/2.1.0/markdown-features/admonitions

2023-01-11 16:55 UTC, elliotmjackson commented on docs/curl/usage.md
> +of all RPC activity, including server reflection calls.
is it overkill to have a `reference` page, sibling to this `usage` page which highlights err codes, flag description etc. in a data-dump list format that could be referred to in this section(and others like it) as a "for those interested" style.

2023-01-11 18:12 UTC, jhump commented on docs/curl/usage.md
> +`name: value` format. But if it starts with an at-sign (`@`), the rest of the value is interpreted as
I think these are usually referred to as "header names", not "header keys".

2023-01-11 18:36 UTC, jhump commented on docs/curl/usage.md
> +of all RPC activity, including server reflection calls.
I worry about keeping such a page in sync with the code, which is why I put the "run `buf help curl`" bit at the top of the page.

2023-01-11 18:54 UTC, jhump commented on docs/curl/usage.md
> +
Done

2023-01-11 18:55 UTC, jhump commented on docs/curl/usage.md
> +
Interleaved a few examples

2023-01-11 18:55 UTC, jhump commented on docs/curl/usage.md
> +## Request Data and Metadata
I rearranged. Not exactly like your suggestion, but in the same vein. WDYT?

2023-01-11 18:56 UTC, jhump commented on docs/curl/usage.md
> +a [BSR](../bsr/introduction.md) module.
I added one example, using the BSR as an example. I was hoping the link to the `inputs.md` page might suffice for the user seeing how they work.

2023-01-11 19:05 UTC, elliotmjackson commented on docs/curl/usage.md
> +of all RPC activity, including server reflection calls.
totally understand.

2023-01-11 19:27 UTC, elliotmjackson commented on docs/curl/usage.md
> +   https://demo.connect.build/buf.connect.demo.eliza.v1.ElizaService/Introduce
```suggestion
$ buf curl \
  --schema buf.build/bufbuild/eliza \
  --data '{"name": "Bob Loblaw"}' \
  https://demo.connect.build/buf.connect.demo.eliza.v1.ElizaService/Introduce
```
NIT: odd formatting

2023-01-11 21:23 UTC, jhump commented on docs/curl/usage.md
> +   https://demo.connect.build/buf.connect.demo.eliza.v1.ElizaService/Introduce
LOL. I thought I was making it pretty ASCII art by aligning the slashes 😛

2023-01-11 21:25 UTC, jhump commented on docs/curl/usage.md
> +   https://demo.connect.build/buf.connect.demo.eliza.v1.ElizaService/Introduce
fixed

2023-01-11 21:28 UTC, elliotmjackson approved these changes

2023-01-12 17:05 UTC, stefanvanburen commented
@jhump these are great - I thought I already saw this mentioned, and could be done in a separate PR, but should we also update [How To -> Call gRPC Endpoints (CLI)](https://docs.buf.build/how-to/grpc)? Seems like a great place to call out `buf curl`.

2023-01-12 17:08 UTC, jhump commented
@stefanvanburen, thanks for pointing that out! @elliotmjackson did in fact make a comment along those same lines, but I didn't interpret it correctly because I didn't realize that particular page existed. It definitely needs to be changed before merging this PR.

2023-01-12 18:55 UTC, merged