Buf data model documentation
bufbuild/docs.buf.build pull request #406
Opened 2023-02-23 21:34 UTC by elliotmjackson

2023-03-08 14:30 UTC, elliotmjackson commented on vercel.json
> +      "destination": "/bsr/dependency-management:path*"
```suggestion
      "destination": "/bsr/module/dependency-management:path*"
```

2023-03-08 16:35 UTC, elliotmjackson commented on docs/bsr/module/dependency-management.md
> +### 1. Create a Repository
```suggestion
### 1. Create a Repository {#create-a-repository}
```

2023-03-10 21:05 UTC, maryelizbeth requested changes
Some small grammar bits or questions,  but content-wise looks great!

2023-03-10 21:05 UTC, maryelizbeth commented on docs/bsr/user/configure.md
> +Coming soon.
If this is coming soon, it may be useful to put in the title like: 

### Avatar (Coming Soon) 

we will of course have to remove it once it arrives!

2023-03-10 21:05 UTC, maryelizbeth commented on docs/bsr/user/manage.md
> +When signing up for the Buf Schema Registry. You will need to verify your email address by clicking a link sent in an
```suggestion
When signing up for the Buf Schema Registry, you will need to verify your email address by clicking a link sent in an
```

2023-03-10 21:30 UTC, rodaine commented on docs/bsr/module/manage.md
> +developing modules by referring to the "Developing and publishing modules" resource.
link?

2023-03-10 21:30 UTC, rodaine commented on docs/bsr/module/manage.md
> +To create a Buf module, you should start by collecting one or more related protobuf packages within a module, each
```suggestion
To create a Buf module, you should start by collecting one or more related Protobuf packages within a module, each
```

2023-03-10 21:30 UTC, rodaine commented on docs/bsr/repository/configure.md
> +In beta, you get unlimited free private repositories' with your Buf Schema Registry user account and organization.
```suggestion
In beta, you get unlimited free private repositories with your Buf Schema Registry user account and organization.
```

That said, I think we should remove this with the incoming paid tiers looming.

2023-03-10 21:30 UTC, rodaine commented on docs/bsr/repository/manage.md
> +some bigger ones are officially maintained by Buf. These include
```suggestion
some bigger ones are officially maintained by Buf. These include:
```

2023-03-10 21:30 UTC, rodaine commented on docs/bsr/repository/manage.md
> +
Perhaps mention the search functionality? I imagine we're exploring other discovery options?

2023-03-10 21:30 UTC, rodaine commented on docs/bsr/repository/manage.md
> +Buf Schema Registry repository is capable of containing multiple versions of Buf modules, which are stored as **tags**.
```suggestion
Buf Schema Registry repository is capable of containing multiple versions of Buf modules, which are stored as **commits** and **tags**.
```

2023-03-10 21:32 UTC, rodaine commented on docs/generate/managed-mode.md
>  # Standardize your file options with Managed mode
Also noticed in some docs we use H1 as the top-level header, and in others we use us H2. Perhaps we need to do a consistency pass (not necessary now, this patch is quite enough).

2023-03-10 21:44 UTC, elliotmjackson commented on docs/bsr/code-generation.md
> +and [remote packages](remote-packages/overview.mdx) feature for additional details.
hmmm... yes, i though merge these a delete repeats. My bad

2023-03-10 21:44 UTC, elliotmjackson commented on docs/bsr/module/configure.md
> +   `<module-name>:<draft-name>`
good question

2023-03-10 21:47 UTC, elliotmjackson commented on docs/generate/managed-mode.md
>  # Standardize your file options with Managed mode
H1 will replace the title, h2 does not

2023-03-10 21:53 UTC, elliotmjackson commented on docs/bsr/user/configure.md
> +Once you have signed up for the BSR, you have the option to link a source code URL later in the [settings page][settings].
```suggestion
Once you have signed up for the BSR, you have the option to link a URL later in the [settings page][settings].
```

2023-03-13 14:42 UTC, elliotmjackson commented on docs/bsr/module/configure.md
> +</figure>
We don't, I can put in a feature request for the new platform but I'm not keen on adding anything to the new to the existing one.

2023-03-14 13:44 UTC, maryelizbeth approved these changes
LGTM; ty for incorporating our feedback so quickly!

2023-03-14 13:47 UTC, merged