WIP: node-oriented buf CLI Getting Started
bufbuild/docs.buf.build pull request #408
Opened 2023-02-24 14:34 UTC by dimitropoulos

_WIP_

2023-02-24 15:21 UTC, elliotmjackson requested changes

2023-02-24 15:21 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +npm install @bufbuild/protoc-gen-es @bufbuild/protoc-gen-connect-es
```suggestion
npm install @bufbuild/protobuf@^1.0.0 @bufbuild/connect-web@^0.7.0
```

2023-02-24 15:21 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +    out: src/gen
```suggestion
  - plugin: buf.build/bufbuild/es
    opt: target=ts
    out: src/gen
```

2023-02-24 15:21 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +    out: src/gen
```suggestion
  - plugin: buf.build/bufbuild/connect-es
    opt: target=ts
    out: src/gen
```

2023-02-24 15:21 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +npm install @bufbuild/protoc-gen-es @bufbuild/protoc-gen-connect-es
i think these dependencies deserve an explanation

2023-02-24 15:21 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +     "@bufbuild/protoc-gen-es": "^1.0.0",
```suggestion
     "@bufbuild/protobuf": "^1.0.0",
     "@bufbuild/connect-web": "^0.7.0",
```

2023-02-24 15:21 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> ++    "generate": "buf generate proto"
i think this should be called out, maybe linked to the `generate` manual

2023-02-24 15:21 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +
do we assume a version of node?

2023-02-24 15:21 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +
no managed mode?

2023-02-24 15:21 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +## 4 Detect breaking changes {#detect-breaking-changes}
youve removed the Ignore lint failures section, why?

2023-02-24 15:21 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +Once you've determined that your change is breaking, you can revert it, or move the new proto file to `/proto/pet/v1` {@Eliot: help, is this the right thing to do?}
im not sure what youre trying to do?

2023-02-24 15:21 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +## 5 Implement an API
a goal of our getting started guides is to achieve "10 minutes to wow" of which there are two goals:
1. keep it short, which you have done.
2. have a "wow moment". I don't believe this has been achieved, yet.

2023-02-24 15:27 UTC, dimitropoulos commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +(cd proto && npx buf mod init)
great question:

1. to avoid the situation of having them `cd` around back and forth.  This is literally the only command that can't be run from the root, and if we do it this way we avoid the whole topic.
1. it's much more standard in this world to have npm scripts you run from the root (and never, otherwise, `cd`ing around)

2023-02-24 16:19 UTC, dimitropoulos commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +Place your first proto file in `/proto/pet/v1/pet.proto`:
Sure! I'd just as much rather put it at `/proto/pet.proto` to keep things simple, but I wasn't sure if that'd offend any protobuf-organizational sensibilities.

And with that, I'm not sure I really know, myself, what we should say about this structure.  Could you help with that sentence or two?  I'm totally open to it if it's important!

2023-02-24 16:23 UTC, dimitropoulos commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +npm install @bufbuild/protoc-gen-es @bufbuild/protoc-gen-connect-es
the next paragraph gives an explanation to both of them:

![Screenshot_20230224_112241](https://user-images.githubusercontent.com/15232461/221231743-a0b2fa83-afdc-4a3f-8985-2fba25f9d30a.png)

Also, this project doesn't use connect-web at all, it's all connect-node (unless I've made a mistake somewhere! haha).

2023-02-24 16:26 UTC, dimitropoulos commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +     "@bufbuild/protoc-gen-es": "^1.0.0",
1. `@bufbuild/protobuf` isn't needed to _generate_ the code.
1. this document doesn't use `connect-web` at all (except by off-hand mention of it at the very end).

2023-02-24 16:27 UTC, dimitropoulos commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> ++    "generate": "buf generate proto"
apologies for my ignorance, but where is "the `generate` manual"?  Do you mean `/docs/reference/buf/buf generate.md`?

2023-02-24 16:28 UTC, dimitropoulos commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +
no particular version that I'm aware of.  We support all current LTS node versions as normal so far as I'm aware.

2023-02-24 16:32 UTC, dimitropoulos commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +## 4 Detect breaking changes {#detect-breaking-changes}
1. there are none left to ignore in this example because it doesn't use `google/type/datetime.proto`
1. in this universe, ignoring errors is (I'm speculating) not a critical thing to know.  It feels like trivia when I'd like us to stay focused on the broad points.  I postulate that people understand that there's probably some way to ignore errors, and they can read more on that if they like, but it's hardly central to the point of this document. 
	- I'm open to be wrong about that postulation if there's some critical path that always has people ignoring errors (perhaps with the google stuff?).  If we decide it's critical, then we'll need to complicate things a bit by adding other files and things earlier (without explanation) by which to tee-up the conversation here.

2023-02-24 16:35 UTC, dimitropoulos commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +Once you've determined that your change is breaking, you can revert it, or move the new proto file to `/proto/pet/v1` {@Eliot: help, is this the right thing to do?}
<details>
<summary>note</summary>

apologies for misspelling your name, I was meaning to double check on that before committing and clearly I failed... 
</details>

my question to you is:
> What exactly should someone do if they wanted to make this breaking change?

If we talk about anything, I think it'd be best to talk about that.  People know how to undo a change.  It's much more interesting (again, _if_ we decide to take the time on this) to cover how you handle breaking changes.  The previous doc left me wondering, almost as if to suggest you _can't_ make breaking changes with protobuf (even if you want to).

2023-02-24 16:42 UTC, dimitropoulos commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +    out: src/gen
I followed our [docs](https://connect.build/docs/node/getting-started/#generate-code) and our [examples](https://github.com/bufbuild/connect-es/blob/main/packages/example/buf.gen.yaml).  Am I missing something (re: managed mode?)?

2023-02-24 16:43 UTC, dimitropoulos commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +    out: src/gen
I followed our [docs](https://connect.build/docs/node/getting-started/#generate-code) and our [examples](https://github.com/bufbuild/connect-es/blob/main/packages/example/buf.gen.yaml).  Am I missing something (re: `name` vs `plugin`?)?

2023-02-24 16:44 UTC, dimitropoulos commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +## Before you begin
good call! 700f1af50ad2e5037c5d37ffcfdb2a254067c7c9

2023-02-24 16:46 UTC, dimitropoulos commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +
is there such a thing for node?  It's not listed in our docs https://docs.buf.build/generate/managed-mode

2023-02-24 16:49 UTC, dimitropoulos commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +## 5 Implement an API
unlike Go, where there's only one path to take, there are many paths (as I listed them) you could take from here to get to "wow".  Put differently, if we achieved a "wow" point with Connect-Node but the reader actually wants to use this in the browser, they'd be quite un-wowed by even the best of Connect-Node server docs because it isn't relevant to them.

I agree with you, but I'm not sure how to "square this circle" if you know what I mean.  Is there a way, perhaps, I could write all three of them and we could make a tabbed interface to let the user tell us which one they care about?

2023-02-24 17:02 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +npm install @bufbuild/protoc-gen-es @bufbuild/protoc-gen-connect-es
section below highlights "we are using remote plugins" this way we dont need to have them install plugins

2023-02-27 20:59 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +    out: src/gen
we are using remote plugins in the revised GS guides. A relatively new feature, your references are likely out of date

2023-02-27 20:59 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +    out: src/gen
we are using remote plugins in the revised GS guides. A relatively new feature, your references are likely out of date

2023-02-27 21:00 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> ++    "generate": "buf generate proto"
thats a reference, it COULD work but probably a bit of a leap for a getting started guide. https://docs.buf.build/generate/overview is probably better

2023-02-27 21:17 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +## 4 Detect breaking changes {#detect-breaking-changes}
i think it would be good to highlight that lint failures can be ignored. We have some goals we want to achieve with a getting started guide, introducing a user to more of the buf offering than they may be initially aware is definitely one of those goals.

In saying that, if you strongly feel that it doesn't have a place here then so be it... you're the author, i cant argue with that.

2023-02-27 21:21 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +Place your first proto file in `/proto/pet/v1/pet.proto`:
1. https://docs.buf.build/best-practices/style-guide
2. https://docs.buf.build/best-practices/module-development

2023-02-27 21:23 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +(cd proto && npx buf mod init)
won't the `$` give us the same result?

2023-03-01 16:36 UTC, dimitropoulos commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +(cd proto && npx buf mod init)
I'm sorry, I don't follow.  What do you mean by "the `$`".  Could you give a concrete example of what change you're suggesting?

2023-03-01 16:37 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +(cd proto && npx buf mod init)
```suggestion
$ cd proto 
$ npx buf mod init
```

2023-03-01 16:44 UTC, dimitropoulos commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +## 4 Detect breaking changes {#detect-breaking-changes}
I appreciate your kindness, but I don't view this as "my document" in any way: it's "Buf's document", and I invite you to poke at it!

I genuinely don't see how instructions on how to ignore lint errors are a part of the most critical and crucial things we want them to know.  That is, I'd be shocked to hear of any linter that doesn't have a way to ignore files.  It's table-stakes for linters and not very interesting or impressive to me personally.  Is there some historical reason (i.e. with other proto linters or something) why this is especially interesting?

2023-03-01 16:51 UTC, timostamm commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +    out: src/gen
If we want to use remote plugins consistently across the board in the docs, using them here as well seems like the right choice. 

I think it's noteworthy though that `plugin: buf.build/bufbuild/es` doesn't pin to a specific version. With the plugins and buf on npmjs.com, local plugins are pinned with the same mechanism as any other dependency, and will also be installed and updated with regular package manager commands. So there are actually advantages in using local plugins.

2023-03-01 16:54 UTC, dimitropoulos commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +Place your first proto file in `/proto/pet/v1/pet.proto`:
I'm aware of this document but to be honest it hasn't done a good job at helping me understand.

For example, take the first claim:

> All files should have a package defined.

<img width="50%" src="https://user-images.githubusercontent.com/15232461/222206209-98f2e42d-5120-4817-8424-eb1b291524ab.png" />

If you click on `(Why?)` it takes you to _this_:

<img width="50%" src="https://user-images.githubusercontent.com/15232461/222206545-fd743636-37cd-498a-b411-2034deb7f8e3.png" />

Not to be crass, but this doesn't help me understand `(Why?)` at all.  Some of the others are better, but I'd really appreciate a more specific suggestion about what precisely you'd like to change, if you have it handy.

2023-03-01 17:02 UTC, elliotmjackson commented on docs/tutorials/getting-started-with-buf-cli-ts.md
> +Place your first proto file in `/proto/pet/v1/pet.proto`:
i agree, the why links are insufficient but the content in the style guide is enough for you to answer your question about structure

2023-03-22 16:21 UTC, closed without merging