Standardise existing explanations
bufbuild/docs.buf.build pull request #412
Opened 2023-02-27 16:22 UTC by elliotmjackson

2023-02-27 20:28 UTC, elliotmjackson commented on docs/format/style.md
> +Remember to regularly incorporate formatting into your development workflow, and
```suggestion
Remember to incorporate formatting into your development workflow, and
```

2023-02-27 22:08 UTC, maryelizbeth commented on docs/breaking/overview.md
> +> overview of the `buf breaking` command.
would _introduction_ work better here instead of overview? (below we state the goal of the page is to provide an overview of `buf breaking`

2023-02-27 22:22 UTC, maryelizbeth requested changes
Some small copy-edits and a suggestion to swap out `overview` for `introduction` at the top of each explanation ✍️

2023-02-27 22:22 UTC, maryelizbeth commented on docs/lint/overview.md
> +With `buf lint`, you have access to an easy-to-use tool that can help you catch enforce consistency early on in the
```suggestion
With `buf lint`, you have access to an easy-to-use tool that can help you catch and enforce consistency early on in the
```

2023-02-27 22:22 UTC, maryelizbeth commented on docs/breaking/overview.md
> +With `buf breaking`, you can ensure that your consumers don't get affected by any unnecessary mistakes leading to
```suggestion
With `buf breaking`, you can ensure that your consumers won't be affected by any unnecessary mistakes leading to
```

2023-02-27 22:22 UTC, maryelizbeth commented on docs/format/style.md
> +readability and maintainability of your codebase. Buf Format provides a simple and powerful solution for enforcing a
```suggestion
readability and maintainability of your codebase. `buf format` provides a simple and powerful solution for enforcing a
```

2023-02-27 22:22 UTC, maryelizbeth commented on docs/format/style.md
> +how to customize your formatting rules, configure your Buf Format settings, and integrate this tool into your
```suggestion
how to customize your formatting rules, configure your `buf format` settings, and integrate this tool into your
```

2023-02-27 22:22 UTC, maryelizbeth commented on docs/format/style.md
> +development workflow. With Buf Format, you can ensure that your Protobuf files are easy to read, easy to maintain, and
```suggestion
development workflow. With `buf format`, you can ensure that your Protobuf files are easy to read, easy to maintain, and
```

2023-02-27 22:22 UTC, maryelizbeth commented on docs/generate/managed-mode.md
> +The problem really comes to a head when it comes to import paths. With
```suggestion
The problem really comes to a head, when it comes to import paths. With
```

2023-02-27 22:22 UTC, maryelizbeth commented on docs/lint/overview.md
> +Run `buf lint --error-format=config-ignore-yaml` to get a minimal set of rules to ignore. So you can enable `lint` today
```suggestion
Run `buf lint --error-format=config-ignore-yaml` to get a minimal set of rules to ignore. You can enable `lint` today
```

2023-02-28 00:53 UTC, maryelizbeth approved these changes

2023-02-28 14:43 UTC, merged