input reference
bufbuild/docs.buf.build pull request #430
Opened 2023-03-09 19:10 UTC by joshcarp

2023-03-10 17:59 UTC, joshcarp commented
@elliotmjackson need help with removing inputs.md without breaking old links

2023-03-10 18:03 UTC, elliotmjackson commented
@joshcarp add a redirect to `vercel.json` in root

2023-03-10 18:59 UTC, elliotmjackson commented on docs/reference/inputs.md
>  title: Inputs
you can delete this page

2023-03-10 19:32 UTC, elliotmjackson commented on sidebars.js
> +                items: [
```suggestion
                collapsed: false,
                items: [
```

2023-03-10 20:28 UTC, elliotmjackson requested changes

2023-03-13 20:33 UTC, maryelizbeth reviewed
Left some stylistic notes and thoughts; Am not solid one way or the other on how we display lists of commands and options - so feel free to pick whichever fits best. Otherwise, LGTM.

2023-03-13 20:33 UTC, maryelizbeth commented on docs/reference/inputs/format.md
> +A Module on the Buf Schema Registry. This uses whatever is in this Module for
```suggestion
A Module on the Buf Schema Registry. This uses whatever is in this module for
```

2023-03-13 20:33 UTC, maryelizbeth commented on docs/reference/inputs/format.md
> +input. Other options include branch, tag, ref, depth, recurse_submodules, strip_components, and subdir, which are
i'm 50/50 on this, while i like the consistency of displaying all commands with `this` style - im worried it will create too much visual crowding with the repetition below

2023-03-13 20:33 UTC, maryelizbeth commented on docs/reference/inputs/index.md
> +The buf command is a powerful tool for managing Protocol Buffers (protobuf) projects. To use the command effectively, it
```suggestion
The `buf` command is a powerful tool for managing Protocol Buffers (Protobuf) projects. To use the command effectively, it
```

2023-03-13 20:33 UTC, maryelizbeth commented on docs/reference/inputs/index.md
> +Formats are used to specify both `schema` formats and also just standard payload data formats, for
```suggestion
Formats are used to specify both `schema` formats and also standard payload data formats, for
```

2023-03-13 20:33 UTC, maryelizbeth commented on docs/reference/inputs/index.md
> +Flags are sometimes used because buf needs to have more than one input, or the argument of the command is not a schema
```suggestion
Flags are sometimes used because `buf` needs to have more than one input, or the argument of the command is not a schema
```

2023-03-13 20:33 UTC, maryelizbeth commented on docs/reference/inputs/index.md
> +because one is optional, for example with [buf curl].
```suggestion
because one is optional, for example with `buf curl`.
```

2023-03-13 20:33 UTC, maryelizbeth commented on docs/reference/inputs/source.md
> +A source refers to a collection of uncompiled protobuf files, which can be stored in various formats such as git,
```suggestion
A source refers to a collection of uncompiled Protobuf files, which can be stored in various formats such as git,
```

2023-03-13 20:33 UTC, maryelizbeth commented on docs/reference/inputs/source.md
> +directory, module, tar, protofile, or zip. It is important to note that an Image built with buf build is not considered
```suggestion
directory, module, tar, protofile, or zip. It is important to note that an image built with `buf build` is not considered
```

2023-03-14 15:10 UTC, rodaine commented on docs/reference/inputs/format.md
> +| subdir           | string    | subdirectory to use as base directory            | `buf build path/to/archive.tar#format=tar#subdir=bar`         |
```suggestion
| compression      | gzip,zstd | compression to use                               | `buf build image#format=zip,compression=gzip`                 |
| strip_components | integer   | strip first n directories, applied before subdir | `buf build path/to/archive.tar#format=zip,strip_components=2` |
| subdir           | string    | subdirectory to use as base directory            | `buf build path/to/archive.tar#format=zip,subdir=bar`         |
```

2023-03-14 15:11 UTC, rodaine commented on docs/reference/inputs/format.md
> +| compression | gzip,zstd | compression to use | `buf build image#format=bin,compression=gzip` |
```suggestion
| compression | gzip,zstd | compression to use | `buf build image#format=json,compression=gzip` |
```

2023-03-14 15:13 UTC, rodaine commented on docs/reference/inputs/format.md
> +  interpreted as the `bin` Format.
```suggestion
  interpreted as the `bin` format.
```

2023-03-14 15:14 UTC, rodaine commented on docs/reference/inputs/format.md
> +  by default as the `bin` format.
Worth giving an example of `-` with a format option, ex: `-#format=json`

2023-03-14 15:15 UTC, rodaine commented on docs/reference/inputs/format.md
> +buf build path/to/image#format=tar#compression=gzip
```suggestion
buf build path/to/image#format=tar,compression=gzip
```

2023-03-14 15:16 UTC, rodaine commented on docs/reference/inputs/format.md
> +buf export path/to/archive#format=tar#compression=gzip --output=path/to/output
```suggestion
buf export path/to/archive#format=tar,compression=gzip --output=path/to/output
```

2023-03-14 15:16 UTC, rodaine commented on docs/reference/inputs/format.md
> +buf convert path/to/archive.zip#format=zip#compression=zstd --from=file.json --to=file.bin --type Person
```suggestion
buf convert path/to/archive.zip#format=zip,compression=zstd --from=file.json --to=file.bin --type Person
```

2023-03-14 15:17 UTC, rodaine commented on docs/reference/inputs/format.md
> +When format is `zip` the [compression, subdir, strip_components] options are available.
> [compression, subdir, strip_components]

Does this link correctly?

2023-03-14 15:18 UTC, rodaine commented on docs/reference/inputs/image.md
> +| compression | gzip,zstd | compression to use | `buf build image#format=bin,compression=gzip` |
```suggestion
| compression | gzip,zstd | compression to use | `buf build image#format=json,compression=gzip` |
```

2023-03-14 15:25 UTC, rodaine commented on docs/reference/inputs/source.md
> +The commands that take a source are:
```suggestion
The commands that may take a source are:
```

2023-03-14 15:31 UTC, rodaine commented on docs/reference/inputs/source.md
> +| subdir             | Which subdir to use as base directory   |         | `buf build path/to/archive.tar#format=tar#subdir=bar`                     |
```suggestion
| ref                | A valid git ref                         | HEAD    | `buf build https://github.com/foo/bar#format=git,ref=my_branch`           |
| branch             | A valid git branch                      | HEAD    | `buf build path/to/module#format=git,branch=my_branch`                    |
| tag                | A valid git tag                         |         | `buf build https://github.com/foo/bar#format=git,tag=v1.0.0`          |
| depth              | A valid git depth                       | 50      | `buf build path/to/module#format=git,depth=1`                             |
| recurse_submodules | Whether to clone submodules recursively | false   | `buf build https://github.com/foo/bar#format=git,recurse_submodules=true` |
| subdir             | Which subdir to use as base directory   |         | `buf build path/to/archive.tar#format=git,subdir=bar`                     |
```

2023-03-14 15:31 UTC, rodaine commented on docs/reference/inputs/source.md
> +| subdir           | string    | subdirectory to use as base directory            | `buf build path/to/archive.tar#format=tar#subdir=bar`         |
```suggestion
| compression      | gzip,zstd | compression to use                               | `buf build image#format=tar,compression=gzip`                 |
| strip_components | integer   | strip first n directories, applied before subdir | `buf build path/to/archive.tar#format=tar,strip_components=2` |
| subdir           | string    | subdirectory to use as base directory            | `buf build path/to/archive.tar#format=tar,subdir=bar`         |
```

2023-03-14 15:32 UTC, rodaine commented on docs/reference/inputs/source.md
> +| subdir           | string    | subdirectory to use as base directory            | `buf build path/to/archive.tar#format=tar#subdir=bar`         |
```suggestion
| compression      | gzip,zstd | compression to use                               | `buf build image#format=zip,compression=gzip`                 |
| strip_components | integer   | strip first n directories, applied before subdir | `buf build path/to/archive.tar#format=zip,strip_components=2` |
| subdir           | string    | subdirectory to use as base directory            | `buf build path/to/archive.tar#format=zip,subdir=bar`         |
```

2023-03-14 15:33 UTC, rodaine commented on docs/reference/inputs/source.md
> +buf export path/to/archive#format=tar#compression=gzip --output=path/to/output
```suggestion
buf export path/to/archive#format=tar,compression=gzip --output=path/to/output
```

2023-03-14 15:33 UTC, rodaine commented on docs/reference/inputs/source.md
> +buf convert path/to/archive.zip#format=zip#compression=zstd --from=file.json --to=file.bin --type Person
```suggestion
buf convert path/to/archive.zip#format=zip,compression=zstd --from=file.json --to=file.bin --type Person
```

2023-03-14 15:58 UTC, joshcarp commented on docs/reference/inputs/format.md
> +When format is `zip` the [compression, subdir, strip_components] options are available.
This isn't meant to be a link but more of a placeholder syntax. I think that something like
```suggestion
When format is `zip` the `[compression|subdir|strip_components]` options are available.
```
would be more correct.

I think i need to think about this a little more

2023-03-14 21:17 UTC, joshcarp commented on docs/reference/inputs/format.md
> +format associated with them. Depending on the format other options are available for configuration.
That hasn't been written yet. I can put it on the todo list but i think that's out of scope for this PR

2023-03-14 21:17 UTC, joshcarp commented on docs/reference/inputs/format.md
> +| Format                  | Description           | Derived extension | Example                                           |
I changed it to `Automatically derived formats and compressions` because i think that's clearer than what it is at the moment

2023-03-14 21:20 UTC, joshcarp commented on docs/reference/inputs/format.md
> +input. Other options include branch, tag, ref, depth, recurse_submodules, strip_components, and subdir, which are
I think it's fine tbh, the inline code style we're using isn't as dramatic compared to github anyway so it doesn't look as drastic

2023-03-14 21:22 UTC, joshcarp commented on docs/reference/inputs/authentication.md
> +`buf` looks for a netrc file at `$NETRC` first, defaulting to `~/.netrc`.
Linked

2023-03-15 18:57 UTC, joshcarp commented on docs/reference/inputs/format.md
> +  by default as the `bin` format.
I've added those examples to the sections that they're in

2023-03-16 21:05 UTC, merged