Billing & Subscription documentation
bufbuild/docs.buf.build pull request #431
Opened 2023-03-10 15:49 UTC by elliotmjackson

2023-03-13 18:49 UTC, maryelizbeth requested changes
Reviewed everything but `Types` docs for clarity, punctuation, and consistency. All suggestions optional - let me know if there are any questions.

2023-03-13 18:49 UTC, maryelizbeth commented on docs/bsr/faq.md
> +   The tiers range from a free plan for small projects, to higher tiers for larger projects and enterprise-level
```suggestion
   The tiers range from a free plan for small projects to higher tiers for larger projects and enterprise-level
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/bsr/faq.md
> +   Yes, Buf Schema Registry offers a free plan that you can use to test out the product and see if it meets your needs.
```suggestion
   Yes, Buf Schema Registry offers a free plan that you can use to test out the product to see if it meets your needs.
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/bsr/faq.md
> +   Buf Schema Registry takes data security seriously and uses industry-standard security protocols to keep your data
```suggestion
   Buf Schema Registry  uses industry-standard security protocols to keep your data
```

not an essential change, but the first bit creates too much room for interpretation of what _seriously_ means. tightening the answer gives users clearer guidance about what we are (and are not) doing

2023-03-13 18:49 UTC, maryelizbeth commented on docs/bsr/faq.md
> +   to integrate with your existing development workflow.
```suggestion
   to incorporate into your existing development workflow.
```

removes double use of integrate; incorporate may sound too stuffy - so feel free to grab a better synonym

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/faq.md
> +[Buf Subscriptions](#) come in three levels:
```suggestion
[Buf Subscriptions](#) come in three tiers:
```

using tiers to be consistent with industry language

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/faq.md
> +Professional and Team subscriptions feature additional features, support, consumption levels and more. You can compare
```suggestion
Professional and Team subscriptions feature additional features, support, consumption levels, and more. You can compare
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/faq.md
> +Our Enterprise package includes an Isolated Single-Tenant instance, which enables large organizations to use Buf Schema
```suggestion
Our Enterprise package includes an isolated single-tenant instance, which enables large organizations to use Buf Schema
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/faq.md
> +Upgrading your legacy plan to a Team plan offers you unlimited private repos.For information on how to upgrade to a Team
```suggestion
Upgrading your legacy plan to a Team plan offers you unlimited private repos. For information on how to upgrade to a Team plan,
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/faq.md
> +available in the Free plan. For example, you may need to convert any private repositories to public repositories. For
```suggestion
available in the Free plan. For example, you may need to convert existing private repositories to public repositories. For
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/faq.md
> +Enterprise accounts can contact the Buf team for a proposal and invoice. For Team & Professional accounts, purchasing
Would we want to add a contact link here?

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/faq.md
> +Customers will receive an email invoice each monthly billing period. A subscription confirmation with a link to
```suggestion
Customers will receive an email invoice each monthly billing period and a subscription confirmation with a link to
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/faq.md
> +Team starts at $100 USD per month for the first 100 types and each bucket of 100 types thereafter
```suggestion
Professional starts at $100 USD per month for the first 100 types and each increment of 100 types thereafter
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/faq.md
> +Team starts at $50 USD per month for the first 100 types and each bucket of 100 types thereafter.
```suggestion
Team starts at $50 USD per month for the first 100 types and each increment of 100 types thereafter.
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/faq.md
> +Buf also sends an email notification `Action Required - Credit Card Payment Failed` with an attached unpaid invoice
```suggestion
Buf also sends an email notification with the subject `Action Required - Credit Card Payment Failed`, with an attached unpaid invoice
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/faq.md
> +- Confirmation of paid invoices.
```suggestion
- Confirmation of paid invoices.
- Notification of payment failures
- Usage overage alerts
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/faq.md
> +organization administrators when usage has progressed beyond the previously billed 100-Type bucket. Additionally, you
```suggestion
organization administrators when usage has progressed beyond the previously billed 100-Type increment, Additionally, you
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/index.md
> +Professional, Team, and Enterprise.
```suggestion
Team, Professional, and Enterprise.
```

swap team and pro in order to preserve price order

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/index.md
> +While Buf offers a free version of the Buf Schema Registry, we want to provide even greater development improvements to
```suggestion
While Buf offers a free version of the Buf Schema Registry, we want to provide an improved development experience to
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/index.md
> +Types and no alerts will be sent until they reach that level of usage. An email alert will be sent at each level beyond
```suggestion
Types, and no alerts will be sent until they reach that level of usage. An email alert will be sent at each level beyond
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/index.md
> +clients.
```suggestion
organization.
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/index.md
> +Buf Professional encompasses all the features of Buf Team and more, such as unlimited organizations and advanced
```suggestion
Buf Professional encompasses all the features of Buf Team as well as unlimited organizations and advanced
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/index.md
> +collaboration and management tools. These include team and organization management with custom SSO using SAML and OIDC
```suggestion
collaboration and management tools. These include team and organization management with SSO support for SAML and OIDC
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/index.md
> +**Buf Enterprise** is designed to meet the long-term governance, deployment, and service commitments of enterprises that
```suggestion
**Buf Enterprise** is designed to meet the long-term governance, deployment, and service commitments of organizations that
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/manage.md
> +You can upgrade from Buf Community to a Professional or Team. When
```suggestion
You can upgrade from Buf Community to a Professional or Team plan. When
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/manage.md
> +- If the average number of Types pushed to your registry exceeds 100, you will be charged at the next tier.
```suggestion
- If the average number of Types pushed to your registry exceeds 100, you will be charged for each additional increment.
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/manage.md
> +   You need to be the owner of the organization to manage its registry
```suggestion
   You need to be the owner of the organization to manage its registry.
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/manage.md
> +3. Select the Organization you manage.
```suggestion
3. Select the Organization you manage
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/manage.md
> +Admins can choose to be notified when usage has progressed into the next tier, based on average number of Types.
```suggestion
Admins can choose to be notified when usage has progressed beyond a specified increment (e.g. 500), based on average number of Types. 
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/migration.md
> +Accessing the BSR will need to be configured to login to your new instance.
```suggestion
In order to access the BSR, you will need to provide login configuration details via the buf CLI.
```

2023-03-13 18:49 UTC, maryelizbeth commented on docs/subscription/migration.md
> +You'll want to run the following with an admin token
```suggestion
To copy dependencies, run the following with an admin token
```

2023-03-14 21:16 UTC, fyockm approved these changes

2023-03-14 21:20 UTC, maryelizbeth approved these changes

2023-03-14 21:21 UTC, merged